site_name: Estrato - Documentação
theme:
  name: material
  logo: assets/simbol-white2.svg
  favicon: assets/simbol-white2.svg

  palette:
    - scheme: default
      primary: grey
      toggle: 
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode

    - scheme: slate
      primary: grey
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 'Visão Geral': 'index.md'
  - 'Backlog': 'backlog.md'
  - 'Diagrama de Classes': 'uml-diagram.md'
  - 'Protótipo de Alta Fidelidade': 'prototype.md'